### 修改的第一个方法：GetBuildArea

```c#
//获得每栋建筑中某种类型的面积分区
public static Dictionary<string, List<Area>> GetBuildArea(Autodesk.Revit.DB.Document document, string AreaTypeName, List<Element> elementsGrids)
{
    Dictionary<string, List<Area>> FireArea_buildNum = new Dictionary<string, List<Area>>();
    //根据轴网获取了所有的可能的楼栋
    foreach (var ele in elementsGrids)
    {
        string build_num_might = Utils.StartSubString(ele.Name, 0, "-");
        if (build_num_might != "" || build_num_might != null || build_num_might != " ")
        {
            if (!FireArea_buildNum.ContainsKey(build_num_might))
            {
                FireArea_buildNum.Add(build_num_might, new List<Area>());
            }
        }
    }
    FireArea_buildNum.Add("B1", new List<Area>());
    FireArea_buildNum.Add("B2", new List<Area>());
    FireArea_buildNum.Add("B3", new List<Area>());
    FireArea_buildNum.Add("B4", new List<Area>());
    FireArea_buildNum.Add("B5", new List<Area>());
    FireArea_buildNum.Add("b1", new List<Area>());
    FireArea_buildNum.Add("b2", new List<Area>());
    FireArea_buildNum.Add("b3", new List<Area>());
    FireArea_buildNum.Add("b4", new List<Area>());
    FireArea_buildNum.Add("b5", new List<Area>());
    int area_num = 0;
    string area_buildnum;
    //过滤得到所有面积分区Area，然后按照名字过滤，得到指定类型的面积分区
    FilteredElementCollector AreaCollector = new FilteredElementCollector(document).OfCategory(BuiltInCategory.OST_Areas);
    foreach (Area area in AreaCollector)
    {
        if (area.AreaScheme.Name.Contains(AreaTypeName))
        {
            if (area.Name.Contains("B"))
            {
                area_buildnum = Utils.LastSubEndString(area.Name, AreaTypeName);//先分离出防火分区后面的字段，例如“B1-1 1”
                area_buildnum = Utils.StartSubString(area_buildnum, 0, "-", false, true);//然后获得楼号，例如“B1”
                FireArea_buildNum[area_buildnum].Add(area);
                //stringBuilder.AppendLine("防火分区Id：" + area.Id + "，名称：" + area.Name + "，楼号：" + area_buildnum + "#");
                area_num++;
            }
            else
            {
                area_buildnum = Utils.LastSubEndString(area.Name, AreaTypeName);//先分离出防火分区后面的字段，例如“1#-2F-1 10”
                area_buildnum = Utils.StartSubString(area_buildnum, 0, "#-");//然后获得楼号，例如“1”
                FireArea_buildNum[area_buildnum].Add(area);
                //stringBuilder.AppendLine("防火分区Id：" + area.Id + "，名称：" + area.Name + "，楼号：" + area_buildnum + "#");
                area_num++;
            }
        }
    }
    return FireArea_buildNum;
}
```

### 修改的第二个方法：GetBuildPipe

```c#
//根据过滤好的管道数组，判断每栋建筑有哪些管道
public static Dictionary<string, List<Pipe>> GetBuildPipe(Autodesk.Revit.DB.Document document, List<Pipe> PipeList, List<Element> elementsGridsSort, List<Element> elementsGrids)
{
    double buildMinX = 0; //建筑最小的X坐标
    double buildMinY = 0; //建筑最小的Y坐标
    double buildMaxX = 0; //建筑最大的X坐标
    double buildMaxY = 0; //建筑最大的Y坐标
    double buildMinZ = 0; //建筑最大的Z坐标
    double buildMaxZ = 0; //建筑最大的Z坐标

    double PipeMaxX; //消防立管的最大X坐标
    double PipeMinX; //消防立管的最小X坐标
    double PipeMaxY; //消火的最大Y坐标
    double PipeMinY; //消防立管的最小Y坐标
    double PipeMaxZ; //消防立管的最大Z坐标
    double PipeMinZ; //消防立管的最小Z坐标
    double PipeXLength; //消防立管的X轴长度
    double PipeYLength; //消防立管的Y轴长度
    double PipeZLength; //消防立管的Z轴长度

    Dictionary<string, List<Pipe>> Pipe_buildNum = new Dictionary<string, List<Pipe>>();
    //根据轴网获取了所有的可能的楼栋
    foreach (var ele in elementsGrids)
    {
        string build_num_might = Utils.StartSubString(ele.Name, 0, "-");
        if (build_num_might != "" || build_num_might != null || build_num_might != " ")
        {
            if (!Pipe_buildNum.ContainsKey(build_num_might))
            {
                Pipe_buildNum.Add(build_num_might, new List<Pipe>());
            }
        }
    }
    Pipe_buildNum.Add("B1", new List<Pipe>());
    Pipe_buildNum.Add("B2", new List<Pipe>());
    Pipe_buildNum.Add("B3", new List<Pipe>());
    Pipe_buildNum.Add("B4", new List<Pipe>());
    Pipe_buildNum.Add("B5", new List<Pipe>());
    Pipe_buildNum.Add("b1", new List<Pipe>());
    Pipe_buildNum.Add("b2", new List<Pipe>());
    Pipe_buildNum.Add("b3", new List<Pipe>());
    Pipe_buildNum.Add("b4", new List<Pipe>());
    Pipe_buildNum.Add("b5", new List<Pipe>());
    string item_name;
    string pre_item_name = "0";

    //Dictionary<Element, List<double>> FirePipeXYZ = new Dictionary<Element, List<double>>();
    //找到每栋楼的喷淋管
    foreach (var item in elementsGridsSort)
    {
        //stringBuilder.AppendLine("ele.Name：" + ele.Name + "，ele.Id：" + ele.Id + "，ele.LevelId：" + ele.LevelId);
        //stringBuilder.AppendLine(StartSubString(ele.Name, 0, "-"));
        if (item.Name.Contains("-") &&
            !item.Name.Contains(".") &&
            !item.Name.Contains("d-") &&
            !item.Name.Contains("A") &&
            //!item.Name.Contains("B") &&
            !item.Name.Contains("C") &&
            !item.Name.Contains("D") &&
            !item.Name.Contains("1S") &&
            !item.Name.Contains("公") &&
            !item.Name.Contains("测"))
        {
            item_name = Utils.StartSubString(item.Name, 0, "-");
            if (item_name == pre_item_name)//如果轴网不发生变化，就继续求BoundingXYZ的最大最小XY值
            {
                BoundingBoxXYZ buildBoundingBoxXYZ = item.get_BoundingBox(document.ActiveView);//计算轴网建筑的占地范围
                XYZ buildXYZMax = buildBoundingBoxXYZ.Max; //取到Max元组
                XYZ buildXYZMin = buildBoundingBoxXYZ.Min; //取到Min元组
                //stringBuilder.AppendLine("轴网：" + item_name + "的方位：" + "X:(" + buildXYZMin.X + "," + buildXYZMax.X + ")" + "，Y:(" + buildXYZMin.Y + "," + buildXYZMax.Y + ")");
                if (Math.Abs(buildXYZMax.X - buildXYZMin.X) < 5) //如果Max和Min的X变化不大，就认为是一条竖的轴网，就只更新Y
                {
                    buildMaxY = buildXYZMax.Y;
                    buildMinY = buildXYZMin.Y;
                }
                if (Math.Abs(buildXYZMax.Y - buildXYZMin.Y) < 5) //如果Max和Min的Y变化不大，就认为是一条水平的轴网，就只更新X
                {
                    buildMaxX = buildXYZMax.X;
                    buildMinX = buildXYZMin.X;
                }
                buildMinZ = buildXYZMin.Z;
                buildMaxZ = buildXYZMax.Z;
                //stringBuilder.AppendLine(item.Name); 
                //stringBuilder.AppendLine($"更新后的：({Math.Round(buildMinX, 2)},{Math.Round(buildMaxX, 2)}),({Math.Round(buildMinY, 2)},{Math.Round(buildMaxY, 2)}),({Math.Round(buildMinZ, 2)},{Math.Round(buildMaxZ, 2)})");

                //stringBuilder.AppendLine("轴网：" + item_name + "的方位：" + "X:(" + buildMinX + "," + buildMaxX + ")" + "，Y:(" + buildMinY + "," + buildMaxY + ")");
            }
            else //如果前后两个轴网发生变化，说明已经切换到下一栋楼了，打印输出一下这栋楼的占地方位
            {
                //轴网变化，新的建筑占地坐标重新更新，此时进行物品的检测最准确

                //找每个楼栋的喷淋管道
                foreach (var Pipe in PipeList)
                {
                    BoundingBoxXYZ FirePipeBoundingBoxXYZ = Pipe.get_BoundingBox(document.ActiveView);
                    XYZ FirePipeXYZMax = FirePipeBoundingBoxXYZ.Max; //取到Max元组
                    XYZ FirePipeXYZMin = FirePipeBoundingBoxXYZ.Min; //取到Min元组
                    PipeMinX = FirePipeXYZMin.X;
                    PipeMaxX = FirePipeXYZMax.X;
                    PipeMinY = FirePipeXYZMin.Y;
                    PipeMaxY = FirePipeXYZMax.Y;
                    PipeMinZ = FirePipeXYZMin.Z;
                    PipeMaxZ = FirePipeXYZMax.Z;
                    PipeXLength = Math.Round(Utils.FootToMeter(Math.Abs(PipeMaxX - PipeMinX)), 2);
                    PipeYLength = Math.Round(Utils.FootToMeter(Math.Abs(PipeMaxY - PipeMinY)), 2);
                    PipeZLength = Math.Round(Utils.FootToMeter(Math.Abs(PipeMaxZ - PipeMinZ)), 2);
                    //stringBuilder.AppendLine("FirePipe.LevelId：" + FirePipe.LevelId + "，FirePipe.Name：" + FirePipe.Name + "，FirePipeAbbr：" + FirePipe.LookupParameter("系统缩写").AsString() + "，FirePipe.Id：" + FirePipe.Id + "，方位：" + "X:(" + FirePipeMinX + "," + FirePipeMaxX + ")" + "，Y:(" + FirePipeMinY + "," + FirePipeMaxY + ")" + "，Z:(" + FirePipeMinZ + "," + FirePipeMaxZ + ")" + "，Z轴长度：" + FirePipeZLength + "m");
                    //stringBuilder.AppendLine($"{FirePipeXLength},{FirePipeYLength},{FirePipeZLength}");
                    //stringBuilder.AppendLine($"管道：({Math.Round(FirePipeMinX,2)},{Math.Round(FirePipeMaxX,2)}),({Math.Round(FirePipeMinY,2)},{Math.Round(FirePipeMaxY,2)}),({Math.Round(FirePipeMinZ,2)},{Math.Round(FirePipeMaxZ,2)})");
                    //stringBuilder.AppendLine("现在item.Name是：" + item.Name + "，pre_item_name是：" + pre_item_name);
                    //stringBuilder.AppendLine($"楼栋：({Math.Round(buildMinX,2)},{Math.Round(buildMaxX, 2)}),({Math.Round(buildMinY, 2)},{Math.Round(buildMaxY, 2)}),({Math.Round(buildMinZ, 2)},{Math.Round(buildMaxZ,2)})");
                    if (PipeMinX > buildMinX && PipeMinY > buildMinY && PipeMaxX < buildMaxX && PipeMaxY < buildMaxY && !Pipe_buildNum[item_name].Contains(Pipe))
                    {
                        if ((PipeXLength < 1 && PipeYLength < 1 && PipeZLength >= 0.1) || PipeYLength > 0.1 || PipeXLength > 0.1) //筛选出垂直的管道（X,Y偏移量不超过1m，Z轴高度大于0.5m），去掉水平的管道
                        {
                            Pipe_buildNum[pre_item_name].Add(Pipe);

                            //stringBuilder.AppendLine(pre_item_name + "#：" + FirePipe.Id + "，" + FirePipe.LookupParameter("系统缩写").AsString() + "，X：（" + FirePipeMaxX + "，" + FirePipeMinX + "），Y：（" + FirePipeMaxY + "，" + FirePipeMinY + "），Z：(" + FirePipeMinZ + "，" + FirePipeMaxZ + ")");
                        }
                    }
                }
                //stringBuilder.AppendLine("以上是属于" + pre_item_name + "的物品");
                //stringBuilder.AppendLine("轴网变化：" + "前一个轴网：" + pre_item_name + "，现在轴网：" + item_name + "，" + pre_item_name + "的方位：" + "X:(" + buildMinX + "," + buildMaxX + ")" + "，Y:(" + buildMinY + "," + buildMaxY + ")");
                //stringBuilder.AppendLine("轴网变化：" + "前一个轴网：" + pre_item_name + "，现在轴网：" + item_name);
                BoundingBoxXYZ buildBoundingBoxXYZ = item.get_BoundingBox(document.ActiveView);//计算轴网建筑的占地范围
                XYZ buildXYZMax = buildBoundingBoxXYZ.Max; //取到Max元组
                XYZ buildXYZMin = buildBoundingBoxXYZ.Min; //取到Min元组
                buildMinX = buildXYZMin.X; //建筑最小的X坐标
                buildMaxX = buildXYZMax.X; //建筑最大的X坐标
                buildMinY = buildXYZMin.Y; //建筑最小的Y坐标
                buildMaxY = buildXYZMax.Y; //建筑最大的Y坐标
            }
            pre_item_name = item_name;
            //给最后一栋楼匹配管道
            foreach (var FirePipe in PipeList)
            {
                BoundingBoxXYZ FirePipeBoundingBoxXYZ = FirePipe.get_BoundingBox(document.ActiveView);
                XYZ FirePipeXYZMax = FirePipeBoundingBoxXYZ.Max; //取到Max元组
                XYZ FirePipeXYZMin = FirePipeBoundingBoxXYZ.Min; //取到Min元组
                PipeMaxX = FirePipeXYZMax.X;
                PipeMinX = FirePipeXYZMin.X;
                PipeMaxY = FirePipeXYZMax.Y;
                PipeMinY = FirePipeXYZMin.Y;
                PipeMaxZ = FirePipeXYZMax.Z;
                PipeMinZ = FirePipeXYZMin.Z;
                PipeXLength = Math.Round(Utils.FootToMeter(Math.Abs(PipeMaxX - PipeMinX)), 2);
                PipeYLength = Math.Round(Utils.FootToMeter(Math.Abs(PipeMaxY - PipeMinY)), 2);
                PipeZLength = Math.Round(Utils.FootToMeter(Math.Abs(PipeMaxZ - PipeMinZ)), 2);
                //stringBuilder.AppendLine("FirePipe.LevelId：" + FirePipe.LevelId + "，FirePipe.Name：" + FirePipe.Name + "，FirePipeAbbr：" + FirePipe.LookupParameter("系统缩写").AsString() + "，FirePipe.Id：" + FirePipe.Id + "，方位：" + "X:(" + FirePipeMinX + "," + FirePipeMaxX + ")" + "，Y:(" + FirePipeMinY + "," + FirePipeMaxY + ")" + "，Z:(" + FirePipeMinZ + "," + FirePipeMaxZ + ")" + "，Z轴长度：" + FirePipeZLength + "m");
                //stringBuilder.AppendLine($"{FirePipeXLength},{FirePipeYLength},{FirePipeZLength}");
                //stringBuilder.AppendLine($"管道：({Math.Round(FirePipeMinX, 2)},{Math.Round(FirePipeMaxX, 2)}),({Math.Round(FirePipeMinY, 2)},{Math.Round(FirePipeMaxY, 2)}),({Math.Round(FirePipeMinZ, 2)},{Math.Round(FirePipeMaxZ, 2)})");
                //stringBuilder.AppendLine("现在item.Name是：" + item.Name + "，pre_item_name是：" + pre_item_name);
                //stringBuilder.AppendLine($"楼栋：({Math.Round(buildMinX, 2)},{Math.Round(buildMaxX, 2)}),({Math.Round(buildMinY, 2)},{Math.Round(buildMaxY, 2)}),({Math.Round(buildMinZ, 2)},{Math.Round(buildMaxZ, 2)})");
                if (PipeMinX > buildMinX && PipeMinY > buildMinY && PipeMaxX < buildMaxX && PipeMaxY < buildMaxY && !Pipe_buildNum[item_name].Contains(FirePipe))
                {
                    if ((PipeXLength < 1 && PipeYLength < 1 && PipeZLength >= 0.1) || PipeYLength > 0.1 || PipeXLength > 0.1) //筛选出垂直的管道（X,Y偏移量不超过1m，Z轴高度大于0.5m），去掉水平的管道
                    {
                        Pipe_buildNum[pre_item_name].Add(FirePipe);
                        //stringBuilder.AppendLine(pre_item_name + "#：" + FirePipe.Id + "，" + FirePipe.LookupParameter("系统缩写").AsString() + "，X：（" + FirePipeMaxX + "，" + FirePipeMinX + "），Y：（" + FirePipeMaxY + "，" + FirePipeMinY + "），Z：(" + FirePipeMinZ + "，" + FirePipeMaxZ + ")");
                    }
                }
            }
        }
    }
    return Pipe_buildNum;
}
```

### 主函数里的修改代码（放在开头）

```c#
public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elements)
{
    // 轴网收集器
    FilteredElementCollector collectorGrid = new FilteredElementCollector(document);
    //过滤出每栋楼的轴网
    List<Element> elementsGrids = collectorGrid.OfCategory(BuiltInCategory.OST_Grids).ToList<Element>();

    //==========防火分区FireArea==========
    Dictionary<string, List<Area>> FireArea_buildNum = GetBuildArea(document, "防火分区", elementsGrids);

    //==========找到每个轴网范围内的喷淋管道==========
    Dictionary<string, List<Pipe>> FirePipe_buildNum = GetBuildPipe(document, FirePipeList, elementsGridsSort, elementsGrids);
}
```

修改的方法替换旧的方法即可。

主函数里的代码关于轴网部分放在开头，后面两个字典替换旧的代码即可。

其他代码都不用管。
